version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    volumes:
      - minecraftdata:/data
      - ./plugins:/plugins
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "BUKKIT"
      OPS: "Wessim"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      DIFFICULTY: "hard"
      SERVER_NAME: "Survie MC"
    tty: true
    stdin_open: true
    restart: unless-stopped

  mcsmanager:
    image: mcsmanager:latest
    ports:
      - "23333:23333"
    volumes:
      - ./mcsmanagerdata:/data
    restart: unless-stopped

volumes:
  minecraftdata:
    external: true
